apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: postgresql
    type: postgres
    access: proxy
    url: postgres:5432
    database: dislocation_trader
    user: trader
    secureJsonData:
      password: devpassword
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: false
