ALTER TABLE pm_live_trades
  ADD COLUMN IF NOT EXISTS win_score NUMERIC(8,4),
  ADD COLUMN IF NOT EXISTS cap_score NUMERIC(8,4),
  ADD COLUMN IF NOT EXISTS cal_prob NUMERIC(8,4),
  ADD COLUMN IF NOT EXISTS kelly_size NUMERIC(12,4);
